import { AppProvider } from '../utils/context/useAppContext'
import Layout from '../components/layout/Layout'

import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <AppProvider>
      <Layout
        title="NASA Challenge"
        description="Generated by Federico Tanco"
        keywords="NASA, Challenge, Federico Tanco, southern code "
      >
        <Component {...pageProps} />
      </Layout>
    </AppProvider>
  )
}

export default MyApp
